# Generated by Django 5.2.6 on 2025-09-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Website",
        ),
    ]
