# Generated by Django 5.2.6 on 2025-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_delete_favorite_delete_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
