# Generated by Django 5.2.6 on 2025-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_address', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('website_name', models.CharField(max_length=100)),
            ],
        ),
    ]
