# Generated by Django 5.2.6 on 2025-10-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='login.user'),
        ),
    ]
